### PR TITLE
Added screenshots according to issue #2

### PR DESCRIPTION
**Pull request by StefanJanssen95**

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Looks good! Can we embed them in the README with an h3 above each one saying which language it's showing?

**Comment by StefanJanssen95** [comment]
Will do that first thing tomorrow.

**Comment by StefanJanssen95** [comment]
Is this how you wanted it?

**Comment by shakeelmohamed** [comment]
@StefanJanssen95 Phenomenal job, thank you so much! Happy hacking 🎃

**Pull request merged**
